
extern yunofile_status __stdcall open_yunofile_manually (const char*, int, void*, yunosize, yunofile*);
extern yunofile_status __stdcall open_async_yunofile_manually (const char*, int, void*, yunosize, yunofile*);
extern yunofile __stdcall *open_yunofile (const char*, int, yunosize);
extern yunofile __stdcall *open_async_yunofile (const char*, int, yunosize);
extern bool __stdcall yunofile_readablep (yunofile*);
extern bool __stdcall yunofile_writablep (yunofile*);
extern yunofile_status __stdcall write_yunofile (void*, yunosize, yunofile*, yunosize*);
extern yunofile_status __stdcall request_write_yunofile (void*, yunosize, yunofile*);
extern yunofile_status __stdcall wait_write_yunofile (yunofile_wait_mode, yunofile*, yunosize*);
extern yunofile_status __stdcall read_yunofile (void*, yunosize, yunofile*, yunosize*);
extern yunofile_status __stdcall request_read_yunofile (yunosize, yunofile*);
extern yunofile_status __stdcall wait_read_yunofile (void*, yunofile_wait_mode, yunofile*, yunosize*);
extern yunofile_status __stdcall seek_yunofile (yunossize, yunofile_where, yunofile*, yunosize*);
extern yunofile_status __stdcall tell_yunofile (yunofile*, yunosize*);
extern yunofile_status __stdcall close_yunofile (yunofile*);
extern yunofile_status __stdcall free_yunofile (yunofile*);
extern yunofile_status __stdcall open_yunostandard_input_manually (void*, yunosize, yunofile*);
extern yunofile_status __stdcall open_yunostandard_output_manually (void*, yunosize, yunofile*);
extern yunofile_status __stdcall open_yunostandard_error_manually (void*, yunosize, yunofile*);
extern yunofile_status __stdcall open_async_yunostandard_input_manually (void*, yunosize, yunofile*);
extern yunofile_status __stdcall open_async_yunostandard_output_manually (void*, yunosize, yunofile*);
extern yunofile_status __stdcall open_async_yunostandard_error_manually (void*, yunosize, yunofile*);
extern yunofile __stdcall *open_yunostandard_input (yunosize);
extern yunofile __stdcall *open_yunostandard_output (yunosize);
extern yunofile __stdcall *open_yunostandard_error (yunosize);
extern yunofile __stdcall *open_async_yunostandard_input (yunosize);
extern yunofile __stdcall *open_async_yunostandard_output (yunosize);
extern yunofile __stdcall *open_async_yunostandard_error (yunosize);
