
extern yunofile_status __yunocall open_yunofile_manually (const char*, int, void*, yunosize, yunofile*);
extern yunofile_status __yunocall open_async_yunofile_manually (const char*, int, void*, yunosize, yunofile*);
extern yunofile __yunocall *open_yunofile (const char*, int, yunosize);
extern yunofile __yunocall *open_async_yunofile (const char*, int, yunosize);
extern bool __yunocall yunofile_readablep (yunofile*);
extern bool __yunocall yunofile_writablep (yunofile*);
extern yunofile_status __yunocall write_yunofile (void*, yunosize, yunofile*, yunosize*);
extern yunofile_status __yunocall request_write_yunofile (void*, yunosize, yunofile*);
extern yunofile_status __yunocall wait_write_yunofile (yunofile_wait_mode, yunofile*, yunosize*);
extern yunofile_status __yunocall read_yunofile (void*, yunosize, yunofile*, yunosize*);
extern yunofile_status __yunocall request_read_yunofile (yunosize, yunofile*);
extern yunofile_status __yunocall wait_read_yunofile (void*, yunofile_wait_mode, yunofile*, yunosize*);
extern yunofile_status __yunocall seek_yunofile (yunossize, yunofile_where, yunofile*, yunosize*);
extern yunofile_status __yunocall tell_yunofile (yunofile*, yunosize*);
extern yunofile_status __yunocall close_yunofile (yunofile*);
extern yunofile_status __yunocall free_yunofile (yunofile*);
extern yunofile_status __yunocall get_yunostandard_input_manually (void*, yunosize, yunofile*);
extern yunofile_status __yunocall get_yunostandard_output_manually (void*, yunosize, yunofile*);
extern yunofile_status __yunocall get_yunostandard_error_manually (void*, yunosize, yunofile*);
extern yunofile_status __yunocall get_async_yunostandard_input_manually (void*, yunosize, yunofile*);
extern yunofile_status __yunocall get_async_yunostandard_output_manually (void*, yunosize, yunofile*);
extern yunofile_status __yunocall get_async_yunostandard_error_manually (void*, yunosize, yunofile*);
extern yunofile __yunocall *get_yunostandard_input (yunosize);
extern yunofile __yunocall *get_yunostandard_output (yunosize);
extern yunofile __yunocall *get_yunostandard_error (yunosize);
extern yunofile __yunocall *get_async_yunostandard_input (yunosize);
extern yunofile __yunocall *get_async_yunostandard_output (yunosize);
extern yunofile __yunocall *get_async_yunostandard_error (yunosize);
