
typedef enum yunoerror {
	YUNONOERROR=0,
	YUNOERROR,
	YUNOBUSY,
	YUNOARGUMENT_ERROR,
	YUNOALREADY_CLOSED,
	YUNODOES_NOT_EXIST,
	YUNOIS_A_DIRECTORY,
	YUNOPERMISSION_ERROR, 
	YUNOOS_ERROR,
	YUNONOT_ENOUGH_MEMORY,
} yunoerror;
