
.always:

clean: .always
	rm -f yunosize.lib
	rm -f yunosize.private
	rm -f yunosize.public

yunosize.private: yunosize.p
	cp yunosize.p yunosize.private

yunosize.public: yunosize.p
	cp yunosize.p yunosize.public

